USE [master]
GO

/****** Object:  Database [SEHTA]    Script Date: 8/11/2023 1:28:30 a. m. ******/
CREATE DATABASE [SEHTA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SEHTA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL_SERVER\MSSQL\DATA\SEHTA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SEHTA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL_SERVER\MSSQL\DATA\SEHTA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SEHTA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SEHTA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SEHTA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SEHTA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SEHTA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SEHTA] SET ARITHABORT OFF 
GO

ALTER DATABASE [SEHTA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SEHTA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SEHTA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SEHTA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SEHTA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SEHTA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SEHTA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SEHTA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SEHTA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SEHTA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SEHTA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SEHTA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SEHTA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SEHTA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SEHTA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SEHTA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SEHTA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SEHTA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SEHTA] SET  MULTI_USER 
GO

ALTER DATABASE [SEHTA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SEHTA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SEHTA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SEHTA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SEHTA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SEHTA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SEHTA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SEHTA] SET  READ_WRITE 
GO

