//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuedesPasARG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class analisisOrina
    {
        public int id { get; set; }
        public Nullable<double> acido_5_hidrox { get; set; }
        public Nullable<double> acido_vainillin_man { get; set; }
        public Nullable<double> cortisol_libre { get; set; }
        public Nullable<double> epinefrina { get; set; }
        public Nullable<double> metanefrina { get; set; }
        public Nullable<double> norepinefrina { get; set; }
        public Nullable<double> proteinuria { get; set; }
        public Nullable<double> sodio { get; set; }
        public Nullable<double> supr_dexa { get; set; }
        public Nullable<double> tfg { get; set; }
    }
}
