//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuedesPasARG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class analisisSangre
    {
        public int id { get; set; }
        public Nullable<double> arp { get; set; }
        public Nullable<double> conc_aldo { get; set; }
        public Nullable<double> cromogranina_a { get; set; }
        public Nullable<double> dopamina { get; set; }
        public Nullable<double> epinefrina { get; set; }
        public Nullable<double> igf1 { get; set; }
        public Nullable<double> norepinefrina { get; set; }
        public Nullable<double> serotonina { get; set; }
        public Nullable<double> t4 { get; set; }
        public Nullable<double> tsh { get; set; }
    }
}
