//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuedesPasARG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anamnesis
    {
        public int id { get; set; }
        public Nullable<bool> ant_poliquistosis { get; set; }
        public Nullable<bool> cons_drogdas { get; set; }
        public Nullable<bool> cons_farmacos { get; set; }
        public Nullable<bool> cons_otras { get; set; }
    }
}
