//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuedesPasARG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnostico
    {
        public int id { get; set; } //0
        public Nullable<System.DateTime> fecha { get; set; }
        public string nivelPA { get; set; } //2
        public string etiologia { get; set; }//3
        public Nullable<int> idPaciente { get; set; }//4
        public Nullable<int> idAnalisisOrina { get; set; } //5
        public Nullable<int> idAnalisisSangre { get; set; } //6
        public Nullable<int> idPresionArterial { get; set; } //7
        public Nullable<int> idPolisomnografia { get; set; } //8
        public Nullable<int> idEstudioImagen { get; set; } //9
        public Nullable<int> idAnalisisSalival { get; set; }//10
        public string estado { get; set; }
        public string comentario { get; set; }
        public Nullable<int> idAnamnesis { get; set; }
    }
}
