//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuedesPasARG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BaseDatos : DbContext
    {
        public BaseDatos()
            : base("name=BaseDatos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<analisisOrina> analisisOrina { get; set; }
        public virtual DbSet<analisisSalival> analisisSalival { get; set; }
        public virtual DbSet<analisisSangre> analisisSangre { get; set; }
        public virtual DbSet<anamnesis> anamnesis { get; set; }
        public virtual DbSet<diagnostico> diagnostico { get; set; }
        public virtual DbSet<estudioImagen> estudioImagen { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<polisomnografia> polisomnografia { get; set; }
        public virtual DbSet<presionArterial> presionArterial { get; set; }
    
        public virtual int prc_actualizar_diagnostico(Nullable<int> idDiagnostico, string estado, string comentario)
        {
            var idDiagnosticoParameter = idDiagnostico.HasValue ?
                new ObjectParameter("idDiagnostico", idDiagnostico) :
                new ObjectParameter("idDiagnostico", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("comentario", comentario) :
                new ObjectParameter("comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_actualizar_diagnostico", idDiagnosticoParameter, estadoParameter, comentarioParameter);
        }
    
        public virtual int prc_insert_analisis_orina(Nullable<double> acido_5, Nullable<double> acido_vainillin, Nullable<double> cortisol, Nullable<double> epinefrina, Nullable<double> metanefrina, Nullable<double> norepinefrina, Nullable<double> proteinuria, Nullable<double> sodio, Nullable<double> supr_dexa, Nullable<double> tfg, ObjectParameter idInsertado)
        {
            var acido_5Parameter = acido_5.HasValue ?
                new ObjectParameter("acido_5", acido_5) :
                new ObjectParameter("acido_5", typeof(double));
    
            var acido_vainillinParameter = acido_vainillin.HasValue ?
                new ObjectParameter("acido_vainillin", acido_vainillin) :
                new ObjectParameter("acido_vainillin", typeof(double));
    
            var cortisolParameter = cortisol.HasValue ?
                new ObjectParameter("cortisol", cortisol) :
                new ObjectParameter("cortisol", typeof(double));
    
            var epinefrinaParameter = epinefrina.HasValue ?
                new ObjectParameter("epinefrina", epinefrina) :
                new ObjectParameter("epinefrina", typeof(double));
    
            var metanefrinaParameter = metanefrina.HasValue ?
                new ObjectParameter("metanefrina", metanefrina) :
                new ObjectParameter("metanefrina", typeof(double));
    
            var norepinefrinaParameter = norepinefrina.HasValue ?
                new ObjectParameter("norepinefrina", norepinefrina) :
                new ObjectParameter("norepinefrina", typeof(double));
    
            var proteinuriaParameter = proteinuria.HasValue ?
                new ObjectParameter("proteinuria", proteinuria) :
                new ObjectParameter("proteinuria", typeof(double));
    
            var sodioParameter = sodio.HasValue ?
                new ObjectParameter("sodio", sodio) :
                new ObjectParameter("sodio", typeof(double));
    
            var supr_dexaParameter = supr_dexa.HasValue ?
                new ObjectParameter("supr_dexa", supr_dexa) :
                new ObjectParameter("supr_dexa", typeof(double));
    
            var tfgParameter = tfg.HasValue ?
                new ObjectParameter("tfg", tfg) :
                new ObjectParameter("tfg", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_insert_analisis_orina", acido_5Parameter, acido_vainillinParameter, cortisolParameter, epinefrinaParameter, metanefrinaParameter, norepinefrinaParameter, proteinuriaParameter, sodioParameter, supr_dexaParameter, tfgParameter, idInsertado);
        }
    
        public virtual int prc_insert_analisis_salival(Nullable<double> cortisol_nocturno, ObjectParameter idInsertado)
        {
            var cortisol_nocturnoParameter = cortisol_nocturno.HasValue ?
                new ObjectParameter("cortisol_nocturno", cortisol_nocturno) :
                new ObjectParameter("cortisol_nocturno", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_insert_analisis_salival", cortisol_nocturnoParameter, idInsertado);
        }
    
        public virtual int prc_insert_analisis_sangre(Nullable<double> arp, Nullable<double> conc_aldo, Nullable<double> cromogranina, Nullable<double> dopamina, Nullable<double> epinefrina, Nullable<double> igf1, Nullable<double> norepinefrina, Nullable<double> serotonina, Nullable<double> t4, Nullable<double> tsh, ObjectParameter idInsertado)
        {
            var arpParameter = arp.HasValue ?
                new ObjectParameter("arp", arp) :
                new ObjectParameter("arp", typeof(double));
    
            var conc_aldoParameter = conc_aldo.HasValue ?
                new ObjectParameter("conc_aldo", conc_aldo) :
                new ObjectParameter("conc_aldo", typeof(double));
    
            var cromograninaParameter = cromogranina.HasValue ?
                new ObjectParameter("cromogranina", cromogranina) :
                new ObjectParameter("cromogranina", typeof(double));
    
            var dopaminaParameter = dopamina.HasValue ?
                new ObjectParameter("dopamina", dopamina) :
                new ObjectParameter("dopamina", typeof(double));
    
            var epinefrinaParameter = epinefrina.HasValue ?
                new ObjectParameter("epinefrina", epinefrina) :
                new ObjectParameter("epinefrina", typeof(double));
    
            var igf1Parameter = igf1.HasValue ?
                new ObjectParameter("igf1", igf1) :
                new ObjectParameter("igf1", typeof(double));
    
            var norepinefrinaParameter = norepinefrina.HasValue ?
                new ObjectParameter("norepinefrina", norepinefrina) :
                new ObjectParameter("norepinefrina", typeof(double));
    
            var serotoninaParameter = serotonina.HasValue ?
                new ObjectParameter("serotonina", serotonina) :
                new ObjectParameter("serotonina", typeof(double));
    
            var t4Parameter = t4.HasValue ?
                new ObjectParameter("t4", t4) :
                new ObjectParameter("t4", typeof(double));
    
            var tshParameter = tsh.HasValue ?
                new ObjectParameter("tsh", tsh) :
                new ObjectParameter("tsh", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_insert_analisis_sangre", arpParameter, conc_aldoParameter, cromograninaParameter, dopaminaParameter, epinefrinaParameter, igf1Parameter, norepinefrinaParameter, serotoninaParameter, t4Parameter, tshParameter, idInsertado);
        }
    
        public virtual int prc_insert_anamnesis(Nullable<bool> ant_poli, Nullable<bool> cons_drogas, Nullable<bool> cons_farmacos, Nullable<bool> cons_otras, ObjectParameter idInsertado)
        {
            var ant_poliParameter = ant_poli.HasValue ?
                new ObjectParameter("ant_poli", ant_poli) :
                new ObjectParameter("ant_poli", typeof(bool));
    
            var cons_drogasParameter = cons_drogas.HasValue ?
                new ObjectParameter("cons_drogas", cons_drogas) :
                new ObjectParameter("cons_drogas", typeof(bool));
    
            var cons_farmacosParameter = cons_farmacos.HasValue ?
                new ObjectParameter("cons_farmacos", cons_farmacos) :
                new ObjectParameter("cons_farmacos", typeof(bool));
    
            var cons_otrasParameter = cons_otras.HasValue ?
                new ObjectParameter("cons_otras", cons_otras) :
                new ObjectParameter("cons_otras", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_insert_anamnesis", ant_poliParameter, cons_drogasParameter, cons_farmacosParameter, cons_otrasParameter, idInsertado);
        }
    
        public virtual int prc_insert_diagnostico(Nullable<System.DateTime> fecha, string nivelPA, string etiologia, Nullable<int> idPaciente, Nullable<int> idAnalisisOrina, Nullable<int> idAnalisisSangre, Nullable<int> idPresionArterial, Nullable<int> idPolisomnografia, Nullable<int> idEstudioImagen, Nullable<int> idAnalisisSalival, Nullable<int> idAnamnesis, string estado, string comentario, ObjectParameter idInsertado)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var nivelPAParameter = nivelPA != null ?
                new ObjectParameter("nivelPA", nivelPA) :
                new ObjectParameter("nivelPA", typeof(string));
    
            var etiologiaParameter = etiologia != null ?
                new ObjectParameter("etiologia", etiologia) :
                new ObjectParameter("etiologia", typeof(string));
    
            var idPacienteParameter = idPaciente.HasValue ?
                new ObjectParameter("idPaciente", idPaciente) :
                new ObjectParameter("idPaciente", typeof(int));
    
            var idAnalisisOrinaParameter = idAnalisisOrina.HasValue ?
                new ObjectParameter("idAnalisisOrina", idAnalisisOrina) :
                new ObjectParameter("idAnalisisOrina", typeof(int));
    
            var idAnalisisSangreParameter = idAnalisisSangre.HasValue ?
                new ObjectParameter("idAnalisisSangre", idAnalisisSangre) :
                new ObjectParameter("idAnalisisSangre", typeof(int));
    
            var idPresionArterialParameter = idPresionArterial.HasValue ?
                new ObjectParameter("idPresionArterial", idPresionArterial) :
                new ObjectParameter("idPresionArterial", typeof(int));
    
            var idPolisomnografiaParameter = idPolisomnografia.HasValue ?
                new ObjectParameter("idPolisomnografia", idPolisomnografia) :
                new ObjectParameter("idPolisomnografia", typeof(int));
    
            var idEstudioImagenParameter = idEstudioImagen.HasValue ?
                new ObjectParameter("idEstudioImagen", idEstudioImagen) :
                new ObjectParameter("idEstudioImagen", typeof(int));
    
            var idAnalisisSalivalParameter = idAnalisisSalival.HasValue ?
                new ObjectParameter("idAnalisisSalival", idAnalisisSalival) :
                new ObjectParameter("idAnalisisSalival", typeof(int));
    
            var idAnamnesisParameter = idAnamnesis.HasValue ?
                new ObjectParameter("idAnamnesis", idAnamnesis) :
                new ObjectParameter("idAnamnesis", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("comentario", comentario) :
                new ObjectParameter("comentario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_insert_diagnostico", fechaParameter, nivelPAParameter, etiologiaParameter, idPacienteParameter, idAnalisisOrinaParameter, idAnalisisSangreParameter, idPresionArterialParameter, idPolisomnografiaParameter, idEstudioImagenParameter, idAnalisisSalivalParameter, idAnamnesisParameter, estadoParameter, comentarioParameter, idInsertado);
        }
    
        public virtual int prc_insert_estudio_imagen(Nullable<bool> coartacion, Nullable<bool> estenosis, Nullable<int> quistes, ObjectParameter idInsertado)
        {
            var coartacionParameter = coartacion.HasValue ?
                new ObjectParameter("coartacion", coartacion) :
                new ObjectParameter("coartacion", typeof(bool));
    
            var estenosisParameter = estenosis.HasValue ?
                new ObjectParameter("estenosis", estenosis) :
                new ObjectParameter("estenosis", typeof(bool));
    
            var quistesParameter = quistes.HasValue ?
                new ObjectParameter("quistes", quistes) :
                new ObjectParameter("quistes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_insert_estudio_imagen", coartacionParameter, estenosisParameter, quistesParameter, idInsertado);
        }
    
        public virtual int prc_insert_paciente(Nullable<int> dni, string nombre, string apellido, string edad, ObjectParameter idInsertado)
        {
            var dniParameter = dni.HasValue ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var edadParameter = edad != null ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_insert_paciente", dniParameter, nombreParameter, apellidoParameter, edadParameter, idInsertado);
        }
    
        public virtual int prc_insert_polisomnografia(Nullable<int> iah, ObjectParameter idInsertado)
        {
            var iahParameter = iah.HasValue ?
                new ObjectParameter("iah", iah) :
                new ObjectParameter("iah", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_insert_polisomnografia", iahParameter, idInsertado);
        }
    
        public virtual int prc_insert_presion_arterial(Nullable<int> sistolica, Nullable<int> diastolica, ObjectParameter idInsertado)
        {
            var sistolicaParameter = sistolica.HasValue ?
                new ObjectParameter("sistolica", sistolica) :
                new ObjectParameter("sistolica", typeof(int));
    
            var diastolicaParameter = diastolica.HasValue ?
                new ObjectParameter("diastolica", diastolica) :
                new ObjectParameter("diastolica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_insert_presion_arterial", sistolicaParameter, diastolicaParameter, idInsertado);
        }
    }
}
